language: node_js
node_js:
  - "8.4"
cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - nvm install 8.4
  - yarn install
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn test
